services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped  

# instead of running 
#   docker build -t devops .
#   docker run -p 8080:80 devops
# you run 
#   docker compose up --build