name: CI

on:
  push:
    branches: [main]
  pull_request:

# Give the workflow only the permissions it needs
permissions:
  contents: read

jobs:
  build-and-scan:
    name: Build and Security Scan
    runs-on: ubuntu-latest

    steps:
      # 1. Download the repository
      - name: Checkout code
        uses: actions/checkout@v7

      # 2. Build the Docker image
      - name: Build Docker image
        run: docker build -t devops:${{ github.sha }} .

      # 3. Scan the Docker image
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: devops:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true
          #args: --skip-version-check

  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      # 1. Download the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      # 3. Initialize Terraform
      - name: Terraform Init
        run: terraform init -backend=false

      # 4. Check Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check

      # 5. Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate